### PR TITLE
Update grunt-localizr

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by aredridel** [comment]
This will be a major version bump.

**Comment by grawk** [comment]
Should it go into another branch? Or just wait until we do some other branch maintenance?

**Comment by aredridel** [comment]
I'm thinking the time is now.

**Comment by grawk** [comment]
Right, should we cut a 0.x branch from master first?

**Comment by aredridel** [comment]
Yeah, lemme do that, and test some updated dependencies while I'm bumping things.

**Pull request closed without merging**
