### PR TITLE
Make app.render work

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
I want to make this test case pass before merging.. Will work on that locally.

**Comment by aredridel** [comment]
Indeed -- this just shows a problem. I'm actually working it too, and there's some subtle differences in adaro passed an absolute path vs a template name it looks up

**Comment by aredridel** [comment]
With adaro that has https://github.com/krakenjs/adaro/pull/99 in it, this should work. Will rebase these commits with one bumping deps once that's merged.

**Comment by aredridel** [comment]
And it does in fact pass now with adaro 1.0.1

**Comment by grawk** [comment]
:+1:

**Pull request merged**
